[tool.poetry]
name = "archilume"
version = "0.1.0"
description = "A python wrapper for radiance and parallel execution of radiance programmes for buildings and precincts"
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "archilume"}]

[tool.poetry.dependencies]
python = ">=3.12"
pandas = ">=1.5.0"
pillow = ">=9.0.0"
open3d = ">=0.16.0"
numpy = "*"
pywavefront = "^1.3.3"

[tool.poetry.group.dev.dependencies]
pytest = ">=7.0.0"
pytest-mock = ">=3.10.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"