[project]
name = "archilume"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ifcopenshell>=0.8.3.post1",
    "numpy>=2.3.2",
    "open3d>=0.19.0",
    "opencv-python>=4.11.0.86",
    "pandas>=2.3.1",
    "pillow>=11.3.0",
    "pyradiance>=1.1.5",
]

[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["archilume*"]
exclude = ["inputs*", "outputs*", "intermediates*"]

[dependency-groups]
dev = [
    "coverage>=7.10.3",
    "pytest>=8.4.1",
]
